name: Upload Embulk's core packages to GitHub Package Registry
on: [ push ]
jobs:
  embulk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and upload to GitHub Package Registry
      run: ./gradlew publishMavenPublicationToGithubRepository
      env:
        ORG_GRADLE_PROJECT_github_package_user: ${{ secrets.GITHUB_PACKAGE_USER }}
        ORG_GRADLE_PROJECT_github_package_token: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
